openapi: 3.0.1
info:
  title: kycBalanceClientele
  description: API Definition of kycBalanceClientele
  version: 1.0.0
servers:
- url: http://localhost:8290/apcwallets
paths:
  /v1/clientele/{msisdn}:
    get:
      parameters:
      - name: msisdn
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
