openapi: 3.0.1
info:
  title: ApcPaymentAPI
  description: API Definition of ApcPaymentAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/creditservices/APCRecharge
paths:
  /v101:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
