openapi: 3.0.1
info:
  title: ChannelAPIsPBIV2
  description: API Definition of ChannelAPIsPBIV2
  version: 1.0.0
servers:
- url: http://localhost:8290/jazzChannel/V2
paths:
  /bundleSubciption:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
