apiVersion: apps/v1
kind: Deployment
metadata:
  name: <WS02_APP_NAME>
  namespace: wso2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <WS02_APP_NAME>
  template:
    metadata:
      labels:
        app: <WS02_APP_NAME>
    spec:
      containers:
        - name: <WS02_APP_NAME>
          image: default-route-openshift-image-registry.apps.stgocpv1.jazz.com.pk/wso2/<WS02_APP_NAME>:<WS02_APP_TAG>
          ports:
            - containerPort: 8290
            - containerPort: 8253
          env:
            - name: ENV
              value: "staging"
---
apiVersion: v1
kind: Service
metadata:
  name: <WS02_APP_NAME>
  namespace: wso2
spec:
  selector:
    app: <WS02_APP_NAME>
  ports:
    - name: http
      port: 8290
      targetPort: 8290
    - name: https
      port: 8253
      targetPort: 8253
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: <WS02_APP_NAME>
  namespace: wso2
spec:
  to:
    kind: Service
    name: <WS02_APP_NAME>
  port:
    targetPort: http
  tls:
    termination: edge
