apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wso2
  name: <WS02_APP_NAME>
  annotations:
    kubernetes.io/change-cause: "init deploy"
  labels:
    app: <WS02_APP_NAME>
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <WS02_APP_NAME>
  template:
    metadata:
      labels:
        app: <WS02_APP_NAME>
    spec:
      containers:
        - name: <WS02_APP_NAME>
          image: default-route-openshift-image-registry.apps.stgocpv1.jazz.com.pk/wso2/<WS02_APP_NAME>:<WS02_APP_TAG>
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8290
              protocol: TCP
            - containerPort: 8253
              protocol: TCP
            - containerPort: 9201
              protocol: TCP
            - containerPort: 9164
              protocol: TCP
      # Ensure pull from internal registry works
      imagePullSecrets:
        - name: registry-sa-dockercfg-s5n9b   # <- adjust to your namespace's default secret
---
apiVersion: v1
kind: Service
metadata:
  namespace: wso2
  name: <WS02_APP_NAME>-svc
spec:
  selector:
    app: <WS02_APP_NAME>
  ports:
    - name: http
      protocol: TCP
      port: 8290
      targetPort: 8290
    - name: https
      protocol: TCP
      port: 8253
      targetPort: 8253
    - name: mi-internal-http
      protocol: TCP
      port: 9201
      targetPort: 9201
    - name: mi-internal-https
      protocol: TCP
      port: 9164
      targetPort: 9164
  type: ClusterIP
