apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wso2
  name: <WS02_APP_NAME>   # replaced by Jenkins
  annotations:
    kubernetes.io/change-cause: "init deploy"
  labels:
    app: <WS02_APP_NAME>
spec:
  selector:
    matchLabels:
      app: <WS02_APP_NAME>
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0% 
  template:
    metadata:
      labels:
        app: <WS02_APP_NAME>
    spec:
      containers:
        - name: <WS02_APP_NAME>
          image: default-route-openshift-image-registry.apps.stgocpv1.jazz.com.pk/wso2/<WS02_APP_NAME>:<WS02_APP_TAG>
          imagePullPolicy: IfNotPresent
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JVM_MEM_OPTS
              value: "-Xms2g -Xmx3g"
          resources:
           requests:
             memory: "2Gi"
             cpu: "2"
           limits:
             memory: "4Gi"
             cpu: "2"
          ports:
            - containerPort: 8290
            - containerPort: 8253
            - containerPort: 9201
            - containerPort: 9164
---
apiVersion: v1 
kind: Service
metadata:
  namespace: wso2
  name: <WS02_APP_NAME>-svc
spec:
  selector:
    app: <WS02_APP_NAME>
  ports:
    - protocol: "TCP"
      name: "http"
      port: 8290 
      targetPort: 8290 
    - protocol: "TCP"
      name: "https"
      port: 8253 
      targetPort: 8253 
    - protocol: "TCP"
      name: "mi-internal-http"
      port: 9201 
      targetPort: 9201
    - protocol: "mi-internal-https"
      port: 9164 
      targetPort: 9164 
  type: ClusterIP
