openapi: 3.0.1
info:
  title: Jazz_Generic_Bundle_Subscription
  description: API Definition of Jazz_Generic_Bundle_Subscription
  version: 1.0.0
servers:
- url: http://localhost:8290/Jazzchannel/Generic
paths:
  /BundleSubscription:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
