openapi: 3.0.1
info:
  title: Jazz_EasyPaisa
  description: API Definition of Jazz_EasyPaisa
  version: 1.0.0
servers:
- url: http://localhost:8290/jazz_EP
paths:
  /bundleSubsciption:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
