openapi: 3.0.1
info:
  title: ChannelAPIsPBI
  description: API Definition of ChannelAPIsPBI
  version: 1.0.0
servers:
- url: http://localhost:8290/jazzChannel
paths:
  /v1/balance/{uri.var.msisdn}/{uri.var.operator}/{uri.var.type}:
    get:
      parameters:
      - name: uri.var.msisdn
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: uri.var.operator
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: uri.var.type
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /bundleSubciption:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
  /v1/clientele/{msisdn}:
    get:
      parameters:
      - name: msisdn
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
  /checkmsisdn/{uri.var.msisdn}:
    get:
      parameters:
      - name: uri.var.msisdn
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        default:
          description: Default response
