openapi: 3.0.1
info:
  title: Jazzapi_Jazzwallet
  description: API Definition of Jazzapi_Jazzwallet
  version: 1.0.0
servers:
- url: http://localhost:8290/jazz_api/jazzwallet/v1
paths:
  /bundlesubscription:
    post:
      requestBody:
        description: Sample Payload
        content:
          application/json:
            schema:
              type: object
              properties:
                payload:
                  type: object
        required: false
      responses:
        default:
          description: Default response
